apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sonarqube
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
        - name: sonarqube
          image: sonarqube:latest
          resources:
            requests:
              cpu: 500m
              memory: 1024Mi
            limits:
              cpu: 2000m
              memory: 2048Mi
          volumeMounts:
          - mountPath: "/opt/sonarqube/data/"
            name: sonar-data
          - mountPath: "/opt/sonarqube/extensions/"
            name: sonar-extensions
          env:
          - name: "SONARQUBE_JDBC_USERNAME"
            value: "sonar@sonarqubethebest"
          - name: "SONARQUBE_JDBC_URL"
            value: "jdbc:postgresql://sonarqubethebest.postgres.database.azure.com/sonar"
          - name: "SONARQUBE_JDBC_PASSWORD"
            value: "myawesomepassword123!"
          - name: "SONARQUBE_JDBC_SSLMODE"
            value: "require"
          ports:
          - containerPort: 9000
            protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 15
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /
              port: 9000
            initialDelaySeconds: 15
            timeoutSeconds: 30

      initContainers:
        - name: sysctl
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ['sysctl', '-w', 'vm.max_map_count=262144']
          securityContext:
            privileged: true
 
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: sonar-data
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: sonar-extensions
